name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - bokeh
  - cartopy
  - descartes
  - fiona
  - folium
  - gdal
  - geographiclib
  - geojson
  - geopandas
  - geoplot
  - geopy
  - geos=3.7
  - geotiff=1.4
  - ipykernel=5.1
  - ipython=7.1
  - ipywidgets=7.4
  - jupyter=1.0
  - jupyter_client=5.2
  - kealib=1.4
  - matplotlib=3
  - numpy=1.15
  - owslib
  - pandas
  - pillow=5.2
  - proj4=5.2
  - pykdtree=1.3
  - pyproj=1.9
  - pysal
  - rasterio
  - rasterstats=0.13
  - requests=2
  - rtree=0.8
  - scikit-learn=0.20
  - scipy=1.1
  - seaborn=0.9
  - shapely=1.6
  - sqlite=3.26
  - statsmodels=0.9
  - sympy=1.4
  - toolz
  - urllib3
  - verde=1.1.0
  - xarray=0.12

