name: example-environment
channels:
  - conda-forge
  
dependencies:
  - python=3.6
  - bokeh
  - cartopy
  - descartes
  - fiona
  - folium
  - gdal
  - geographiclib
  - geojson
  - geopandas
  - geoplot
  - geopy
  - geos
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyter_client
  - matplotlib
  - numpy
  - owslib
  - pandas
  - pillow=5.2
  - proj4
  - pyproj
  - pysal
  - rasterio
  - rasterstats=0.13
  - requests
  - rtree
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - sympy=1.4
  - toolz
  - urllib3
  - verde
  - xarray
  - poppler

