name: example-environment
channels:
  - https://repo.anaconda.com/pkgs/free
  - conda-forge
  - defaults
dependencies:
  - bokeh=1.0.1
  - cartopy=0.17.0
  - cloudpickle=0.6.1
  - colorama=0.4.0
  - descartes=1.1.0
  - fiona=1.8.4
  - folium=0.6.0
  - gdal=2.4.0
  - geographiclib=1.49
  - geojson=2.4.1
  - geopandas=0.4.0
  - geoplot=0.2.3
  - geopy=1.17.0
  - geos=3.7.1
  - geotiff=1.4.3
  - ipykernel=5.1.0
  - ipython=7.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - jupyterthemes=0.20.0
  - kealib=1.4.10
  - matplotlib=3.0.2
  - matplotlib-base=3.0.1
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - notebook=5.7.0
  - numpy=1.15.4
  - owslib=0.17.0
  - pandas=0.23.4
  - pandoc=2.3.1
  - pandocfilters=1.4.2
  - pillow=5.2.0
  - proj4=5.2.0
  - pygments=2.2.0
  - pykdtree=1.3.1
  - pyproj=1.9.6
  - pysal=1.14.4.post2
  - rasterio=1.0.21
  - rasterstats=0.13.1
  - requests=2.20.0
  - rtree=0.8.3
  - scikit-learn=0.20.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - shapely=1.6.4
  - snappy=1.1.7
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - sympy=1.4
  - toolz=0.9.0
  - urllib3=1.23
  - verde=1.1.0
  - widgetsnbextension=3.4.2 
  - xarray=0.12.1
  - xlrd=1.2.0  
  - zlib=1.2.11

